//AUTH
export const POST_LOGIN = "POST_LOGIN";
export const POST_LOGIN_SUCCESS = "POST_LOGIN_SUCCESS";
export const POST_LOGIN_ERROR = "POST_LOGIN_ERROR";
export const POST_EMPLOYEE_LOGIN = "POST_EMPLOYEE_LOGIN";
export const POST_EMPLOYEE_LOGIN_SUCCESS = "POST_EMPLOYEE_LOGIN_SUCCESS";
export const POST_EMPLOYEE_LOGIN_ERROR = "POST_EMPLOYEE_LOGIN_ERROR";
export const GET_PERMISSION = "GET_PERMISSION";
export const GET_PERMISSION_SUCCESS = "GET_PERMISSION_SUCCESS";
export const GET_PERMISSION_ERROR = "GET_PERMISSION_ERROR";







                    //ADMIN 

//GET EMPLOYEE 
export const GET_EMPLOYEE = "GET_EMPLOYEE";
export const GET_EMPLOYEE_SUCCESS = "GET_EMPLOYEE_SUCCESS";
export const GET_EMPLOYEE_ERROR = "GET_EMPLOYEE_ERROR";
export const GET_BY_ID_EMPLOYEE = "GET_BY_ID_EMPLOYEE";
export const GET_BY_ID_EMPLOYEE_SUCCESS = "GET_BY_ID_EMPLOYEE_SUCCESS";
export const GET_BY_ID_EMPLOYEE_ERROR = "GET_BY_ID_EMPLOYEE_ERROR";
export const POST_EMPLOYEE = "POST_EMPLOYEE";
export const POST_EMPLOYEE_SUCCESS = "POST_EMPLOYEE_SUCCESS";
export const POST_EMPLOYEE_ERROR = "POST_EMPLOYEE_ERROR";
export const PUT_EMPLOYEE = "PUT_EMPLOYEE";
export const PUT_EMPLOYEE_SUCCESS = "PUT_EMPLOYEE_SUCCESS";
export const PUT_EMPLOYEE_ERROR = "PUT_EMPLOYEE_ERROR";
export const DELETE_EMPLOYEE = "DELETE_EMPLOYEE";
export const DELETE_EMPLOYEE_SUCCESS = "DELETE_EMPLOYEE_SUCCESS";
export const DELETE_EMPLOYEE_ERROR = "DELETE_EMPLOYEE_ERROR";
export const BLOCKED_EMPLOYEE = "BLOCKED_EMPLOYEE";
export const BLOCKED_EMPLOYEE_SUCCESS = "BLOCKED_EMPLOYEE_SUCCESS";
export const BLOCKED_EMPLOYEE_ERROR = "BLOCKED_EMPLOYEE_ERROR";




                    //ROLE
export const GET_ROLE = "GET_ROLE";
export const GET_ROLE_SUCCESS = "GET_ROLE_SUCCESS";
export const GET_ROLE_ERROR = "GET_ROLE_ERROR";
export const GET_BY_ID_ROLE = "GET_BY_ID_ROLE";
export const GET_BY_ID_ROLE_SUCCESS = "GET_BY_ID_ROLE_SUCCESS";
export const GET_BY_ID_ROLE_ERROR = "GET_BY_ID_ROLE_ERROR";
export const POST_ROLE = "POST_ROLE";
export const POST_ROLE_SUCCESS = "POST_ROLE_SUCCESS";
export const POST_ROLE_ERROR = "POST_ROLE_ERROR";
export const PUT_ROLE = "PUT_ROLE";
export const PUT_ROLE_SUCCESS = "PUT_ROLE_SUCCESS";
export const PUT_ROLE_ERROR = "PUT_ROLE_ERROR";
export const DELETE_ROLE = "DELETE_ROLE";
export const DELETE_ROLE_SUCCESS = "DELETE_ROLE_SUCCESS";
export const DELETE_ROLE_ERROR = "DELETE_ROLE_ERROR";

                    //Photo Id
export const GET_PHOTOID = "GET_PHOTOID";
export const GET_PHOTOID_SUCCESS = "GET_PHOTOID_SUCCESS";
export const GET_PHOTOID_ERROR = "GET_PHOTOID_ERROR";
export const GET_BY_ID_PHOTOID = "GET_BY_ID_PHOTOID";
export const GET_BY_ID_PHOTOID_SUCCESS = "GET_BY_ID_PHOTOID_SUCCESS";
export const GET_BY_ID_PHOTOID_ERROR = "GET_BY_ID_PHOTOID_ERROR";
export const POST_PHOTOID = "POST_PHOTOID";
export const POST_PHOTOID_SUCCESS = "POST_PHOTOID_SUCCESS";
export const POST_PHOTOID_ERROR = "POST_PHOTOID_ERROR";
export const PUT_PHOTOID = "PUT_PHOTOID";
export const PUT_PHOTOID_SUCCESS = "PUT_PHOTOID_SUCCESS";
export const PUT_PHOTOID_ERROR = "PUT_PHOTOID_ERROR";
export const DELETE_PHOTOID = "DELETE_PHOTOID";
export const DELETE_PHOTOID_SUCCESS = "DELETE_PHOTOID_SUCCESS";
export const DELETE_PHOTOID_ERROR = "DELETE_PHOTOID_ERROR";


                    //TERMINATE
export const GET_TERMINATE = "GET_TERMINATE";
export const GET_TERMINATE_SUCCESS = "GET_TERMINATE_SUCCESS";
export const GET_TERMINATE_ERROR = "GET_TERMINATE_ERROR";
export const POST_TERMINATE = "POST_TERMINATE";
export const POST_TERMINATE_SUCCESS = "POST_TERMINATE_SUCCESS";
export const POST_TERMINATE_ERROR = "POST_TERMINATE_ERROR";


                    //user
export const GET_USER = "GET_USER";
export const GET_USER_SUCCESS = "GET_USER_SUCCESS";
export const GET_USER_ERROR = "GET_USER_ERROR";
export const GET_USER_BY_ID = "GET_USER_BY_ID";
export const GET_USER_BY_ID_SUCCESS = "GET_USER_BY_ID_SUCCESS";
export const GET_USER_BY_ID_ERROR = "GET_USER_BY_ID_ERROR";
export const POST_USER = "POST_USER";
export const POST_USER_SUCCESS = "POST_USER_SUCCESS";
export const POST_USER_ERROR = "POST_USER_ERROR";
export const PUT_USER = "PUT_USER";
export const PUT_USER_SUCCESS = "PUT_USER_SUCCESS";
export const PUT_USER_ERROR = "PUT_USER_ERROR";


                    //LOAN_TYPE
export const GET_LOAN_TYPE = "GET_LOAN_TYPE";
export const GET_LOAN_TYPE_SUCCESS = "GET_LOAN_TYPE_SUCCESS";
export const GET_LOAN_TYPE_ERROR = "GET_LOAN_TYPE_ERROR";
export const GET_BY_ID_LOAN_TYPE = "GET_BY_ID_LOAN_TYPE";
export const GET_BY_ID_LOAN_TYPE_SUCCESS = "GET_BY_ID_LOAN_TYPE_SUCCESS";
export const GET_BY_ID_LOAN_TYPE_ERROR = "GET_BY_ID_LOAN_TYPE_ERROR";
export const POST_LOAN_TYPE = "POST_LOAN_TYPE";
export const POST_LOAN_TYPE_SUCCESS = "POST_LOAN_TYPE_SUCCESS";
export const POST_LOAN_TYPE_ERROR = "POST_LOAN_TYPE_ERROR";
export const PUT_LOAN_TYPE = "PUT_LOAN_TYPE";
export const PUT_LOAN_TYPE_SUCCESS = "PUT_LOAN_TYPE_SUCCESS";
export const PUT_LOAN_TYPE_ERROR = "PUT_LOAN_TYPE_ERROR";
export const DELETE_LOAN_TYPE = "DELETE_LOAN_TYPE";
export const DELETE_LOAN_TYPE_SUCCESS = "DELETE_LOAN_TYPE_SUCCESS";
export const DELETE_LOAN_TYPE_ERROR = "DELETE_LOAN_TYPE_ERROR";


                    //STATE
export const GET_STATE = "GET_STATE";
export const GET_STATE_SUCCESS = "GET_STATE_SUCCESS";
export const GET_STATE_ERROR = "GET_STATE_ERROR";
export const GET_BY_ID_STATE = "GET_BY_ID_STATE";
export const GET_BY_ID_STATE_SUCCESS = "GET_BY_ID_STATE_SUCCESS";
export const GET_BY_ID_STATE_ERROR = "GET_BY_ID_STATE_ERROR";
export const POST_STATE = "POST_STATE";
export const POST_STATE_SUCCESS = "POST_STATE_SUCCESS";
export const POST_STATE_ERROR = "POST_STATE_ERROR";
export const PUT_STATE = "PUT_STATE";
export const PUT_STATE_SUCCESS = "PUT_STATE_SUCCESS";
export const PUT_STATE_ERROR = "PUT_STATE_ERROR";
export const DELETE_STATE = "DELETE_STATE";
export const DELETE_STATE_SUCCESS = "DELETE_STATE_SUCCESS";
export const DELETE_STATE_ERROR = "DELETE_STATE_ERROR";

                    //City
export const GET_CITY = "GET_CITY";
export const GET_CITY_SUCCESS = "GET_CITY_SUCCESS";
export const GET_CITY_ERROR = "GET_CITY_ERROR";
export const GET_BY_ID_CITY = "GET_BY_ID_CITY";
export const GET_BY_ID_CITY_SUCCESS = "GET_BY_ID_CITY_SUCCESS";
export const GET_BY_ID_CITY_ERROR = "GET_BY_ID_CITY_ERROR";
export const POST_CITY = "POST_CITY";
export const POST_CITY_SUCCESS = "POST_CITY_SUCCESS";
export const POST_CITY_ERROR = "POST_CITY_ERROR";
export const PUT_CITY = "PUT_CITY";
export const PUT_CITY_SUCCESS = "PUT_CITY_SUCCESS";
export const PUT_CITY_ERROR = "PUT_CITY_ERROR";
export const DELETE_CITY = "DELETE_CITY";
export const DELETE_CITY_SUCCESS = "DELETE_CITY_SUCCESS";
export const DELETE_CITY_ERROR = "DELETE_CITY_ERROR";


                    //Region
export const GET_REGION = "GET_REGION";
export const GET_REGION_SUCCESS = "GET_REGION_SUCCESS";
export const GET_REGION_ERROR = "GET_REGION_ERROR";
export const GET_BY_ID_REGION = "GET_BY_ID_REGION";
export const GET_BY_ID_REGION_SUCCESS = "GET_BY_ID_REGION_SUCCESS";
export const GET_BY_ID_REGION_ERROR = "GET_BY_ID_REGION_ERROR";
export const POST_REGION = "POST_REGION";
export const POST_REGION_SUCCESS = "POST_REGION_SUCCESS";
export const POST_REGION_ERROR = "POST_REGION_ERROR";
export const PUT_REGION = "PUT_REGION";
export const PUT_REGION_SUCCESS = "PUT_REGION_SUCCESS";
export const PUT_REGION_ERROR = "PUT_REGION_ERROR";
export const DELETE_REGION = "DELETE_REGION";
export const DELETE_REGION_SUCCESS = "DELETE_REGION_SUCCESS";
export const DELETE_REGION_ERROR = "DELETE_REGION_ERROR";


                            //loan
export const GET_LOAN = "GET_LOAN";
export const GET_LOAN_SUCCESS = "GET_LOAN_SUCCESS";
export const GET_LOAN_ERROR = "GET_LOAN_ERROR";
export const GET_LOAN_DOWNLOAD = "GET_LOAN_DOWNLOAD";
export const GET_LOAN_DOWNLOAD_SUCCESS = "GET_LOAN_DOWNLOAD_SUCCESS";
export const GET_LOAN_DOWNLOAD_ERROR = "GET_LOAN_DOWNLOAD_ERROR";
export const GET_BY_ID_LOAN = "GET_BY_ID_LOAN";
export const GET_BY_ID_LOAN_SUCCESS = "GET_BY_ID_LOAN_SUCCESS";
export const GET_BY_ID_LOAN_ERROR = "GET_BY_ID_LOAN_ERROR";
export const GET_BY_USERID_LOAN = "GET_BY_USERID_LOAN";
export const GET_BY_USERID_LOAN_SUCCESS = "GET_BY_USERID_LOAN_SUCCESS";
export const GET_BY_USERID_LOAN_ERROR = "GET_BY_USERID_LOAN_ERROR";
export const GET_PENDING_LOAN = "GET_PENDING_LOAN";
export const GET_PENDING_LOAN_SUCCESS = "GET_PENDING_LOAN_SUCCESS";
export const GET_PENDING_LOAN_ERROR = "GET_PENDING_LOAN_ERROR";
export const POST_LOAN = "POST_LOAN";
export const POST_LOAN_SUCCESS = "POST_LOAN_SUCCESS";
export const POST_LOAN_ERROR = "POST_LOAN_ERROR";
export const POST_LOAN_PAYMENT = "POST_LOAN_PAYMENT";
export const POST_LOAN_PAYMENT_SUCCESS = "POST_LOAN_PAYMENT_SUCCESS";
export const POST_LOAN_PAYMENT_ERROR = "POST_LOAN_PAYMENT_ERROR";
export const PUT_LOAN = "PUT_LOAN";
export const PUT_LOAN_SUCCESS = "PUT_LOAN_SUCCESS";
export const PUT_LOAN_ERROR = "PUT_LOAN_ERROR";
export const PUT_CLOSE_LOAN = "PUT_CLOSE_LOAN";
export const PUT_CLOSE_LOAN_SUCCESS = "PUT_CLOSE_LOAN_SUCCESS";
export const PUT_CLOSE_LOAN_ERROR = "PUT_CLOSE_LOAN_ERROR";

