name: Deploy React to EC2 for Multiple Domains

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Deploy App
    runs-on: ubuntu-latest

    steps:
      - name: SSH and Deploy
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_IP }}
          username: ubuntu
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            cd ~/sagar-testing
            git pull origin main
            npm install -f
            sudo chmod -R 777 node_modules

            # ===== DOMAIN1.COM ======
            cp ~/envs/apple.inditech.shop.env .env
            npm run build
            mkdir -p ~/var/www/html/apple-inditech-shop
            rm -rf ~/var/www/html/apple-inditech-shop/*
            mv dist/* ~/var/www/html/apple-inditech-shop

            # ===== DOMAIN2.COM =====
            cp ~/envs/ball.inditech.shop.env .env
            npm run build
            mkdir -p ~/var/www/html/ball-inditech-shop
            rm -rf ~/var/www/html/ball-inditech-shop/*
            mv dist/* ~/var/www/html/ball-inditech-shop
